version: "3.9"

services:
  database:
    image: mariadb
    container_name: wp-database
    restart: unless-stopped
    networks:
      - wordpress
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_LOCAL_HOME}:/var/lib/mysql:delegated
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  wordpress:
    build: .
    container_name: wp-wordpress
    restart: unless-stopped
    networks:
      - wordpress
    depends_on:
      - database
    env_file:
      - ./.env
    volumes:
      - ./scripts/post-install.sh:/usr/local/bin/post-install
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${WORDPRESS_UPLOADS_CONFIG}:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}

  nginx:
    image: nginx:latest
    container_name: wp-nginx
    restart: unless-stopped
    networks:
      - wordpress
    depends_on:
      - wordpress
    ports:
      - "8080:80" # http
      - "8443:443" # https
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERTS}:/etc/ssl:ro
      - ${NGINX_LOGS}:/var/log/nginx

networks:
  wordpress:
    name: wp-wordpress
    driver: bridge
